# This workflow will build a Java project with Maven
name: Java CI with Maven in Linux
  
on:
 push:
   branches:
    - master
   pull_request:
    - master
 
jobs:
   build:
     runs-on: ubuntu-latest
     strategy:
        matrix:
           java:[11,8]
     name: Build with Java ${{matrix.java}}      
 
     steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 8
       uses: actions/setup-java@v1
       with:
         java-version: ${{matrix.java}}
     - name: Build with Maven
       run: mvn -f com.detail.app.mydetail/pom.xml clean verify